name: Node CI

on: [push, pull_request_target]

jobs:
    test_PR:
        env:
            PORT: ${{secrets.PORT}}
            GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
            MONGO_URI: ${{secrets.MONGO_URI}}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: npm install
            - run: npm run check-format
            - run: npm run test
            # - run: npm run build
