name: Node CI

on: [push, pull_request_target]

jobs:
    format:
        name: Code Formatter
        runs-on: ubuntu-latest
        steps:
            - name: Node Code Formatter
            - uses: MarvinJWendt/run-node-formatter@stable
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    setupandtestnodejs:
        name: Setup and Test NodeJs
        needs: format
        runs-on: ubuntu-latest
        env:
            PORT: ${{secrets.PORT}}
            GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
            MONGO_URI: ${{secrets.MONGO_URI}}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: npm install
            - run: npm run check-format
            - run: npm run test
            # - run: npm run build