name: Node CI

on: [push, pull_request_target]

jobs:
    Format the Code:
            runs-on: ubuntu-latest
        steps:
            - name: Node Code Formatter
            - uses: MarvinJWendt/run-node-formatter@stable
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    Setup and Test Node.Js:
        needs: Format the code
        runs-on: ubuntu-latest
        env:
            PORT: ${{secrets.PORT}}
            GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
            GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
            MONGO_URI: ${{secrets.MONGO_URI}}

        steps:
            - name: Checkout
            - uses: actions/checkout@v2
            
            - name: Setup Node and Run Tests
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: npm install
            - run: npm run check-format
            - run: npm run test
            # - run: npm run build